### ISSUE TITLE
Load and debug program in RAM without flash using gdb / openocd (-DPICO_NO_FLASH=1)

### ISSUE THREAD

**Issue by perexg** [raspberrypi/pico-feedback#153]
The program loading and debugging procedure for `-DPICO_NO_FLASH=1` compilation option is not documented (gdb / openocd). I went through some trial and error steps to make it work. It would be probably nice to document this. My sequence:

````
elf="program.elf"
gdb -ex "target extended-remote localhost:3333" \
    -ex "monitor reset init" \
    -ex "load ${elf}" \
    -ex "continue" \
    "${elf}"
````

If everything is ok (program is in RAM -  starts at 0x20000000):

````
Remote debugging using localhost:3333
Loading section .text, size 0x838c lma 0x20000000
Loading section .rodata, size 0x19c4 lma 0x20008390
Loading section .binary_info, size 0x1c lma 0x20009d54
Loading section .data, size 0x108 lma 0x20009d70
Start address 0x20000000, load size 40564
Transfer rate: 13 KB/sec, 6760 bytes/write.
Continuing.
````

**Comment by kilograham** [comment]
note that this works for _all_ program types

**Comment by perexg** [comment]
Thank you for the clarification. The _getting started_ guide use `load` + `reset init` sequences which works only for the flash programs. The RAM loading / booting requires the `reset halt` + `load` otherwise you can encounter weird behavior like the USB device enumeration failures (no BUS RESET interrupts) etc. when you jump to the updated RAM program without reset. The `reset init` boots always to flash, of course.

**Comment by kilograham** [comment]
oh, thanks... I didn't realize that was there

@lurch can you fix to move the `monitor reset init` before the `load` in section 6.3

#perexg you see issues with `monitor reset init` then `load`... that's what I used and have never seen an issue...

**Comment by perexg** [comment]
It seems that `monitor reset init` and `monitor reset halt` do both the right job. The only difference is initial PC address (0xf0 or 0x2700). The order of `monitor reset` and `load` commands matters for the no-flash program. I apologize for the confusion.

**Comment by aallan** [comment]
> @lurch can you fix to move the monitor reset init before the load in section 6.3

@lurch Did this get done, or still in backlog?

**Comment by lurch** [comment]
Still in backlog.

**Comment by martin2250** [comment]
For anyone struggling with VSCode and Cortex-Debug: I was able to debug my "no_flash" binary by replacing the `postRestartCommands` in the `launch.json` from the examples with:
```json
"overrideLaunchCommands": [
    "monitor reset init",
    "load ${command:cmake.launchTargetPath}"
],
```
I remember this working without this workaround, maybe something changed in the recent releases of the SDK.

**Comment by lurch** [comment]
I no longer work on the documentation, so transferring this issue to @nathan-contino instead :slightly_smiling_face:

**Comment by vazhnov** [comment]
@perexg , I've just loaded and executed a simple blinker program with such a magic:

```sh
openocd -f interface/cmsis-dap.cfg -f target/rp2350-riscv.cfg \
  -c "adapter speed 1000; \
      init; \
      targets rp2350.rv0; \
      halt; \
      load_image ./blink-asm.elf; \
      reg pc 0x20000000; \
      resume; \
      shutdown"
```

using OpenOCD built from [rp2350-pre1.0-rpi](https://github.com/raspberrypi/openocd/tree/rp2350-pre1.0-rpi) branch.

.ld file:

```linker-script
MEMORY
{
        RAM (rwx)  : ORIGIN = 0x20000000, LENGTH = 520K
}
```

Before, I tried simple

```sh
openocd -f interface/cmsis-dap.cfg -f target/rp2350-riscv.cfg -c "adapter speed 1000; program blink.elf preverify verify reset exit"
```

but it failed with

```
…
Info : RP2350 rev 2, QSPI Flash win w25q32fv/jv id = 0x1640ef size = 4096 KiB in 1024 sectors
Info : RP2xxx ROM API function FC @ 7d6a
**pre-verifying**
Error: checksum mismatch - attempting binary compare
** Programming Started **
Warn : no flash bank found for address 0x20000000
** Programming Finished **
** Verify Started **
Error: checksum mismatch - attempting binary compare
** Verify Failed **
shutdown command invoked
embedded:startup.tcl:1965: Error:
Traceback (most recent call last):
  File "embedded:startup.tcl", line 2029, in program
    program_error {** Verify Failed **} 1
  File "embedded:startup.tcl", line 1965, in program_error
    shutdown error
```
